#!/usr/bin/env python3
"""M8: turn per_event.csv into the tables for the report (data/m8_replay/summary.md)."""
import csv
import os
from collections import defaultdict

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
OUTD = os.path.join(ROOT, 'data', 'm8_replay')

QLAB = {0.06: 'q=0.06 (default)', 0.001: 'q=1e-3', 0.0001: 'q=1e-4', 1e-05: 'q=1e-5'}
FAMLAB = {'stock': 'STOCK', 'gate': 'GATED', 'mahal': 'MAHAL 3sigma'}
AMPS = [5.0, 10.0, 20.0, 45.0, 90.0]
DURS = [1, 2, 5]


def f(x, n=3):
    try:
        v = float(x)
    except (TypeError, ValueError):
        return '--'
    if v != v:
        return '--'
    return ('%.' + str(n) + 'f') % v


def main():
    rows = list(csv.DictReader(open(os.path.join(OUTD, 'per_event.csv'))))
    ev = [r for r in rows if r['event_id'] != '_RUN_']
    run = {r['arm']: r for r in rows if r['event_id'] == '_RUN_'}

    by = defaultdict(list)
    for r in ev:
        by[(r['family'], float(r['q']))].append(r)

    out = []
    out.append('# M8 — robot_localization live-chain replay results\n')
    out.append('> Generated by `analysis/m8/summarize_m8.py`, data `per_event.csv`.')
    out.append('> 45 synthetic injections (5/10/20/45/90° × 1/2/5 frames × 3 epochs),')
    out.append('> consumer `/odometry/gps`, reference `/rtk_odom`. '
               'Peak = max deviation (m) within 2 s after the event.\n')

    # ---- table 1: peak deviation by amplitude x config, all durations pooled
    out.append('## Table 1. Peak position deviation, median / max (m), by amplitude\n')
    keys = sorted(by.keys(), key=lambda k: (k[1], k[0]))
    hdr = '| arm | ' + ' | '.join('%g°' % a for a in AMPS) + ' |'
    out.append(hdr)
    out.append('|' + '---|' * (len(AMPS) + 1))
    for fam, q in keys:
        cells = []
        for a in AMPS:
            v = [float(r['peak_m']) for r in by[(fam, q)]
                 if float(r['amp_deg']) == a and r['peak_m'] not in ('', 'nan')]
            v = [x for x in v if x == x]
            cells.append('%s / %s' % (f(np.median(v)), f(np.max(v))) if v else '--')
        out.append('| %s %s | %s |' % (FAMLAB[fam], QLAB.get(q, q), ' | '.join(cells)))
    out.append('')

    # ---- table 2: peak by duration, 90 deg only
    out.append('## Table 2. 90° injection, median peak (m), by duration\n')
    out.append('| arm | 1 frame | 2 frames | 5 frames |')
    out.append('|---|---|---|---|')
    for fam, q in keys:
        cells = []
        for d in DURS:
            v = [float(r['peak_m']) for r in by[(fam, q)]
                 if float(r['amp_deg']) == 90.0 and int(r['dur']) == d
                 and r['peak_m'] not in ('', 'nan')]
            v = [x for x in v if x == x]
            cells.append(f(np.median(v)) if v else '--')
        out.append('| %s %s | %s |' % (FAMLAB[fam], QLAB.get(q, q), ' | '.join(cells)))
    out.append('')

    # ---- table 3: per-run cost
    out.append('## Table 3. Per-replay cost and baseline\n')
    out.append('| arm | baseline median deviation (m) | gate actions outside injections '
               '| withheld frames outside injections | withheld total over 45 events '
               '| gate actions inside event windows |')
    out.append('|---|---|---|---|---|---|')
    for fam, q in keys:
        tag = 'inj_%s_%s' % (fam, {0.06: 'q060', 0.001: 'q1e3', 0.0001: 'q1e4', 1e-05: 'q1e5'}[q])
        r = run.get(tag)
        if r is None:
            continue
        hw = sum(int(x['withheld']) for x in by[(fam, q)] if x['withheld'] not in ('', '-1'))
        gw = sum(int(x['gate_warns']) for x in by[(fam, q)])
        out.append('| %s %s | %s | %s | %s | %s | %d | %d |'
                   % (FAMLAB[fam], QLAB.get(q, q), f(r['peak_base_m'], 4),
                      f(r['recovery_s'], 4), r['gate_warns'], r['withheld'], hw, gw))
    out.append('')

    # ---- table 3b: the increment the gate sees
    out.append('## Table 3b. Filter yaw per-frame increment and total excursion '
               '(90° injection, median; gate budget 17.0°/frame)\n')
    out.append('| arm | 1 frame: max per-frame / total excursion | 2 frames | 5 frames |')
    out.append('|---|---|---|---|')
    for fam, q in keys:
        cells = []
        for d in DURS:
            sel = [r for r in by[(fam, q)] if float(r['amp_deg']) == 90.0
                   and int(r['dur']) == d and r.get('filt_step_deg') not in ('', None)]
            if sel:
                a = np.median([float(r['filt_step_deg']) for r in sel])
                b2 = np.median([float(r['filt_exc_deg']) for r in sel])
                cells.append('%.1f / %.1f' % (a, b2))
            else:
                cells.append('--')
        out.append('| %s %s | %s |' % (FAMLAB[fam], QLAB.get(q, q), ' | '.join(cells)))
    out.append('')

    # ---- table 4: recovery time, 90 deg
    out.append('## Table 4. Median recovery time (s), 90° injection\n')
    out.append('| arm | 1 frame | 2 frames | 5 frames |')
    out.append('|---|---|---|---|')
    for fam, q in keys:
        cells = []
        for d in DURS:
            v = [float(r['recovery_s']) for r in by[(fam, q)]
                 if float(r['amp_deg']) == 90.0 and int(r['dur']) == d
                 and r['recovery_s'] not in ('', 'nan')]
            cells.append(f(np.median(v), 2) if v else '--')
        out.append('| %s %s | %s |' % (FAMLAB[fam], QLAB.get(q, q), ' | '.join(cells)))
    out.append('')

    p = os.path.join(OUTD, 'summary.md')
    open(p, 'w').write('\n'.join(out) + '\n')
    print('\n'.join(out))


if __name__ == '__main__':
    main()
