#!/usr/bin/env python3
"""M8b: tables for data/m8b_measurement_gate/summary.md.

Mirrors analysis/m8/summarize_m8.py's tables 1/2/3/3b/4 but puts the two new arms next to
the three M8 arms.  The M8 rows are read from data/m8_replay/per_event.csv (read-only, not
re-run); the new rows from data/m8b_measurement_gate/per_event.csv.
"""
import csv
import os
from collections import defaultdict

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
OUTD = os.path.join(ROOT, 'data', 'm8b_measurement_gate')
M8D = os.path.join(ROOT, 'data', 'm8_replay')

QLAB = {0.06: 'q=0.06 (default)', 0.001: 'q=1e-3', 0.0001: 'q=1e-4', 1e-05: 'q=1e-5'}
QTAG = {0.06: 'q060', 0.001: 'q1e3', 0.0001: 'q1e4', 1e-05: 'q1e5'}
FAMLAB = {'stock': 'STOCK', 'gate': 'GATED (node-side)', 'mahal': 'MAHAL 3sigma',
          'meas': '**MEAS-GATE (measurement-side)**', 'both': 'MEAS+NODE'}
FAMORD = {'stock': 0, 'gate': 1, 'mahal': 2, 'meas': 3, 'both': 4}
AMPS = [5.0, 10.0, 20.0, 45.0, 90.0]
DURS = [1, 2, 5]


def f(x, n=3):
    try:
        v = float(x)
    except (TypeError, ValueError):
        return '--'
    if v != v:
        return '--'
    return ('%.' + str(n) + 'f') % v


def med(v):
    v = [x for x in v if x == x]
    return np.median(v) if v else float('nan')


def main():
    rows = list(csv.DictReader(open(os.path.join(M8D, 'per_event.csv'))))
    rows += list(csv.DictReader(open(os.path.join(OUTD, 'per_event.csv'))))
    ev = [r for r in rows if r['event_id'] != '_RUN_']
    run = {r['arm']: r for r in rows if r['event_id'] == '_RUN_'}

    by = defaultdict(list)
    for r in ev:
        by[(r['family'], float(r['q']))].append(r)
    keys = sorted(by.keys(), key=lambda k: (k[1], FAMORD[k[0]]))

    out = []
    out.append('# M8b — replay results with the gate moved to the measurement side (EKF input)\n')
    out.append('> Generated by `analysis/m8b/summarize_m8b.py`; the data for the new arms is `per_event.csv`,')
    out.append('> the STOCK / GATED / MAHAL arms are **quoted directly from the M8 `data/m8_replay/per_event.csv`, not re-run**.')
    out.append('> 45 synthetic injections (5/10/20/45/90° × 1/2/5 frames × 3 epochs), consumer `/odometry/gps`,')
    out.append('> reference `/rtk_odom`. Peak = largest deviation within 2 s after the event (m).\n')
    out.append('> **MEAS-GATE** = unpatched `ws_stock` + measurement-side gate (the gate sits on the EKF imu0 input);')
    out.append('> **MEAS+NODE** = `ws_gate` node-side gate + measurement-side gate. The gate rule and parameters of both are identical word for word to GATED.\n')

    out.append('## Table 1 Peak position deviation, median / max (m), by amplitude\n')
    out.append('| Arm | ' + ' | '.join('%g°' % a for a in AMPS) + ' |')
    out.append('|' + '---|' * (len(AMPS) + 1))
    for fam, q in keys:
        cells = []
        for a in AMPS:
            v = [float(r['peak_m']) for r in by[(fam, q)]
                 if float(r['amp_deg']) == a and r['peak_m'] not in ('', 'nan')]
            v = [x for x in v if x == x]
            cells.append('%s / %s' % (f(np.median(v)), f(np.max(v))) if v else '--')
        out.append('| %s %s | %s |' % (FAMLAB[fam], QLAB.get(q, q), ' | '.join(cells)))
    out.append('')

    out.append('## Table 2 90° injection, by duration in frames, median peak (m)\n')
    out.append('| Arm | 1 frame | 2 frames | 5 frames |')
    out.append('|---|---|---|---|')
    for fam, q in keys:
        cells = []
        for d in DURS:
            v = [float(r['peak_m']) for r in by[(fam, q)]
                 if float(r['amp_deg']) == 90.0 and int(r['dur']) == d
                 and r['peak_m'] not in ('', 'nan')]
            cells.append(f(med(v)) if v else '--')
        out.append('| %s %s | %s |' % (FAMLAB[fam], QLAB.get(q, q), ' | '.join(cells)))
    out.append('')

    out.append('## Table 3 Per-replay cost and baseline\n')
    out.append('> "position withheld" = position frames the consumer `/odometry/gps` did not publish (happens only when the gate is node-side);')
    out.append('> "measurement withheld" = heading frames the measurement-side gate did not hand to the EKF (`orientation_covariance[0] = -1`);')
    out.append('> "measurement HOLD" = frames on which the EKF was handed the last accepted, stale heading. All counted outside ±3 s of any injection.\n')
    out.append('| Arm | Baseline median (m) | Baseline p99 (m) | Node gate actions outside injection | Position withheld outside injection | Measurement withheld outside injection | Measurement HOLD outside injection | Position withheld over 45 events | Measurement withheld over 45 events |')
    out.append('|---|---|---|---|---|---|---|---|---|')
    for fam, q in keys:
        tag = 'inj_%s_%s' % (fam, QTAG[q])
        r = run.get(tag)
        if r is None:
            continue
        hw = sum(int(x['withheld']) for x in by[(fam, q)] if x['withheld'] not in ('', '-1'))
        mnp = sum(int(x['meas_nopub']) for x in by[(fam, q)]
                  if x.get('meas_nopub') not in ('', None))
        has = r.get('meas_nopub') not in ('', None)
        out.append('| %s %s | %s | %s | %s | %s | %s | %s | %d | %s |'
                   % (FAMLAB[fam], QLAB.get(q, q), f(r['peak_base_m'], 4),
                      f(r['recovery_s'], 4), r['gate_warns'], r['withheld'],
                      r['meas_nopub'] if has else '--', r['meas_hold'] if has else '--',
                      hw, str(mnp) if has else '--'))
    out.append('')

    out.append('## Table 3b Per-frame increment and total deflection of the filter yaw (90° injection, median; gate budget 17.0°/frame)\n')
    out.append('| Arm | 1 frame max per-frame increment / total deflection | 2 frames | 5 frames |')
    out.append('|---|---|---|---|')
    for fam, q in keys:
        cells = []
        for d in DURS:
            sel = [r for r in by[(fam, q)] if float(r['amp_deg']) == 90.0
                   and int(r['dur']) == d and r.get('filt_step_deg') not in ('', None)]
            if sel:
                cells.append('%.1f / %.1f'
                             % (np.median([float(r['filt_step_deg']) for r in sel]),
                                np.median([float(r['filt_exc_deg']) for r in sel])))
            else:
                cells.append('--')
        out.append('| %s %s | %s |' % (FAMLAB[fam], QLAB.get(q, q), ' | '.join(cells)))
    out.append('')

    out.append('## Table 4 Median recovery time (s), 90° injection\n')
    out.append('| Arm | 1 frame | 2 frames | 5 frames |')
    out.append('|---|---|---|---|')
    for fam, q in keys:
        cells = []
        for d in DURS:
            v = [float(r['recovery_s']) for r in by[(fam, q)]
                 if float(r['amp_deg']) == 90.0 and int(r['dur']) == d
                 and r['recovery_s'] not in ('', 'nan')]
            cells.append(f(med(v), 2) if v else '--')
        out.append('| %s %s | %s |' % (FAMLAB[fam], QLAB.get(q, q), ' | '.join(cells)))
    out.append('')

    p = os.path.join(OUTD, 'summary_tables.md')
    open(p, 'w').write('\n'.join(out) + '\n')
    print('\n'.join(out))


if __name__ == '__main__':
    main()
